workflows:
  build:
    name: Build Simplistic Calculator
    environment:
      flutter: stable # Specify the Flutter channel

    scripts:
      - name: Install dependencies
        script: |
          cd simplistic_calculator
          flutter pub get

      - name: Run Tests
        script: |
          cd simplistic_calculator
          flutter test

      - name: Build Android
        script: |
          cd simplistic_calculator/android
          if [ -f "./gradlew" ]; then
            ./gradlew assembleRelease # Build the release APK
          else
            echo "gradlew not found!"
            exit 1
          fi

      - name: Build iOS
        script: |
          cd simplistic_calculator
          flutter build ios --release --no-codesign

    artifacts:
      - simplistic_calculator/android/app/build/outputs/apk/release/app-release.apk
      - simplistic_calculator/build/ios/iphoneos/*.ipa

  test:
    name: Run Flutter Tests
    scripts:
      - name: Install dependencies
        script: |
          cd simplistic_calculator
          flutter pub get

      - name: Run unit tests
        script: |
          cd simplistic_calculator
          flutter test
